version: '3.7'

services:
  mysql:
    container_name: cad_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cad_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - cad_videos_network

networks:
  cad_videos_network: